/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

int *
addd_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Add for version1 is called...\n");
	int a=argp->a;
	int b=argp->b;
	result = a+b;
	printf("returning result: %d\n",result);
	return &result;
}

int *
mull_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Mul for version1 is called...\n");
	int a=argp->a;
	int b=argp->b;
	result = a*b;
	printf("returning result: %d\n",result);
	return &result;
}

float *
addd_2_svc(floatpair *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	
	printf("Add for version2 is called...\n");
	float a=argp->a;
	float b=argp->b;
	printf("%lf %lf\n",a,b);	

	result = a+b;
	printf("returning result: %f\n",result);
	return &result;
}

float *
mull_2_svc(floatpair *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	printf("Mul for version2 is called...\n");
	float a=argp->a;
	float b=argp->b;
	printf("%f %f\n",a,b);	

	result = a*b;
	printf("returning result: %f\n",result);
	return &result;
}
